// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmxOsaXI2FYSZEGCRFvFqKVdUp_vxo2Fc',
    appId: '1:106475867810:web:4c94ef22affe959bf8d1fb',
    messagingSenderId: '106475867810',
    projectId: 'invitationmaker-5a8f4',
    authDomain: 'invitationmaker-5a8f4.firebaseapp.com',
    storageBucket: 'invitationmaker-5a8f4.appspot.com',
    measurementId: 'G-D4XR62VQD4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxkz_3-J8nlZVyQYpmmgvT8HTDP3fKARw',
    appId: '1:106475867810:android:2a3edf604018c8d1f8d1fb',
    messagingSenderId: '106475867810',
    projectId: 'invitationmaker-5a8f4',
    storageBucket: 'invitationmaker-5a8f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_VKfG4DUodlE07drKX9sMwhIagI6u_HM',
    appId: '1:106475867810:ios:01234020e59a2225f8d1fb',
    messagingSenderId: '106475867810',
    projectId: 'invitationmaker-5a8f4',
    storageBucket: 'invitationmaker-5a8f4.appspot.com',
    iosBundleId: 'com.example.invitationMaker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_VKfG4DUodlE07drKX9sMwhIagI6u_HM',
    appId: '1:106475867810:ios:01234020e59a2225f8d1fb',
    messagingSenderId: '106475867810',
    projectId: 'invitationmaker-5a8f4',
    storageBucket: 'invitationmaker-5a8f4.appspot.com',
    iosBundleId: 'com.example.invitationMaker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmxOsaXI2FYSZEGCRFvFqKVdUp_vxo2Fc',
    appId: '1:106475867810:web:7aa5ca7512b32c9ff8d1fb',
    messagingSenderId: '106475867810',
    projectId: 'invitationmaker-5a8f4',
    authDomain: 'invitationmaker-5a8f4.firebaseapp.com',
    storageBucket: 'invitationmaker-5a8f4.appspot.com',
    measurementId: 'G-2DJWQSD2R1',
  );
}
